import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HeroSection from "@/components/common/HeroSection/HeroSection";
import WhyChoose from "@/components/common/WhyChoose/WhyChoose";
import Packages from "@/components/common/Packages/Packages";
import VisaCard from "@/components/common/VisaCard/VisaCard";
import VisaDetails from "@/components/common/VisaDetails/VisaDetails";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Visa Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${geistSans.variable} ${geistMono.variable}`}>
        <HeroSection />
        <WhyChoose />
        <Packages />
        <VisaDetails />
      </main>

    </>
  );
}
